### ISSUE TITLE
./build.sh hangs

### ISSUE THREAD

**Issue by ghost** [Borim7/radio-tray#6]
/radio-tray-master$ ./build.sh
Traceback (most recent call last):
  File "/home/user/radio-tray-master/setup.py", line 3, in <module>
    from setuptools import setup
ModuleNotFoundError: No module named 'setuptools'

**Comment by Borim7** [comment]
You need to install the dependencies, see https://github.com/Borim7/radio-tray/blob/master/debian/control for what is needed
